"""Write docs/codemap.md: every module of mh4u_rando/ and tools/ with its public API.

Also writes docs/codemap_index.md: one line per module with the line of its
section in codemap.md, so a reader can open just that section.

The map lets a reader (or an AI agent) find where things live without opening
dozens of files. tests/test_codemap.py fails when either file is out of date;
run `python tools/gen_codemap.py` after changing a module's public API.
"""

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "codemap.md"
INDEX_OUTPUT = ROOT / "docs" / "codemap_index.md"
PACKAGES = ("mh4u_rando", "tools")
SUMMARY_WIDTH = 100

HEADER = """# Code map

Generated by `tools/gen_codemap.py` - do not edit by hand (tests/test_codemap.py
checks it is current). One entry per module: its docstring's first line, then
its public classes and functions with their signatures.
"""

INDEX_HEADER = """# Code map index

Generated by `tools/gen_codemap.py` - do not edit by hand. One line per module:
the line where its section starts in `docs/codemap.md`, then the module's
summary. Read only that section of the codemap (from that line to the next
`###`), never the whole file.
"""


def _summary(node: ast.AST) -> str:
    doc = ast.get_docstring(node)
    if not doc:
        return ""
    line = doc.strip().splitlines()[0].strip()
    return line if len(line) <= SUMMARY_WIDTH else line[:SUMMARY_WIDTH - 3] + "..."


def _signature(func: ast.FunctionDef | ast.AsyncFunctionDef, method: bool = False) -> str:
    if method and func.args.args and func.args.args[0].arg in ("self", "cls"):
        func.args.args = func.args.args[1:]
    args = ast.unparse(func.args)
    returns = f" -> {ast.unparse(func.returns)}" if func.returns else ""
    return f"{func.name}({args}){returns}"


def _entry(text: str, summary: str) -> str:
    return f"{text} - {summary}" if summary else text


def _is_public(name: str) -> bool:
    return not name.startswith("_")


def _module_lines(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    rel = path.relative_to(ROOT).as_posix()
    lines = [_entry(f"### `{rel}`", _summary(tree))]
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and _is_public(node.name):
            lines.append(_entry(f"- `{_signature(node)}`", _summary(node)))
        elif isinstance(node, ast.ClassDef) and _is_public(node.name):
            bases = ", ".join(ast.unparse(base) for base in node.bases)
            lines.append(_entry(f"- class `{node.name}({bases})`" if bases else f"- class `{node.name}`",
                                _summary(node)))
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and _is_public(item.name):
                    lines.append(_entry(f"  - `{_signature(item, method=True)}`", _summary(item)))
    return lines


def modules() -> list[Path]:
    paths = []
    for package in PACKAGES:
        paths += [p for p in (ROOT / package).rglob("*.py") if "__pycache__" not in p.parts]
    return sorted(paths, key=lambda p: p.relative_to(ROOT).as_posix())


def build() -> str:
    sections = [HEADER]
    for path in modules():
        sections.append("\n".join(_module_lines(path)) + "\n")
    return "\n".join(sections)


def build_index(codemap: str) -> str:
    """The index of a codemap text: each module section with its starting line."""
    lines = [INDEX_HEADER]
    for number, line in enumerate(codemap.splitlines(), start=1):
        if line.startswith("### "):
            lines.append(f"- L{number}: {line[4:]}")
    return "\n".join(lines) + "\n"


def _write(path: Path, text: str) -> None:
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"updated {path.relative_to(ROOT).as_posix()}")


def main() -> int:
    text = build()
    _write(OUTPUT, text)
    _write(INDEX_OUTPUT, build_index(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
